service: spot-service

provider:
  name: aws
  runtime: java8
  stage: dev
  region: eu-central-1

# you can add packaging information here
package:
  artifact: build/distributions/spots_service.zip

functions:
  getSpots:
    handler: com.juvodu.serverless.handler.GetAllSpotsHandler
    events:
      - http:
          path: spots
          method: get
          cors: true
  getSpot:
      handler: com.juvodu.serverless.handler.GetSpotHandler
      events:
        - http:
            path: spot
            method: get
            cors: true
  createSpot:
    handler: com.juvodu.serverless.handler.CreateSpotHandler
    events:
      - http:
          path: spot
          method: post
          cors: true

# The "Resources" your "Functions" use.  Raw AWS CloudFormation goes in here.
resources:
  Resources:
    SpotTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: spot
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    DynamoDBIamPolicy:
      Type: AWS::IAM::Policy
      DependsOn: SpotTable
      Properties:
        PolicyName: lambda-dynamodb
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:DeleteItem
                - dynamodb:UpdateItem
                - dynamodb:Scan
              Resource: arn:aws:dynamodb:*:*:table/spot
        Roles:
          - Ref: IamRoleLambdaExecution

