service: spot-service

provider:
  name: aws
  runtime: java8
  stage: dev
  region: eu-central-1

# you can add packaging information here
package:
  artifact: build/distributions/spots_service.zip

functions:
  getSpots:
    handler: com.juvodu.serverless.handler.GetAllSpotsHandler
    events:
      - http:
          path: spots
          method: get
          cors: true
  getSpot:
      handler: com.juvodu.serverless.handler.GetSpotByParameterHandler
      events:
        - http:
            path: spot
            method: get
            cors: true
  createSpot:
    handler: com.juvodu.serverless.handler.CreateSpotHandler
    events:
      - http:
          path: spot/create
          method: post
          cors: true
  deleteSpot:
    handler: com.juvodu.serverless.handler.DeleteSpotHandler
    events:
      - http:
          path: spot/delete
          method: post
          cors: true
  updateSpot:
    handler: com.juvodu.serverless.handler.UpdateSpotHandler
    events:
      - http:
          path: spot/update
          method: post
          cors: true

# The "Resources" your "Functions" use.  Raw AWS CloudFormation goes in here.
resources:
  Resources:
    SpotTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: spot
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: continent
            AttributeType: S
          - AttributeName: country
            AttributeType: S
          - AttributeName: geohash
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: continent-country-index
            KeySchema:
              - AttributeName: continent
                KeyType: HASH
              - AttributeName: country
                KeyType: RANGE
            Projection:
                ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: continent-geohash-index
            KeySchema:
              - AttributeName: continent
                KeyType: HASH
              - AttributeName: geohash
                KeyType: RANGE
            Projection:
                ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
    DynamoDBIamPolicy:
      Type: AWS::IAM::Policy
      DependsOn: SpotTable
      Properties:
        PolicyName: lambda-dynamodb
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:DeleteItem
                - dynamodb:UpdateItem
                - dynamodb:Scan
                - dynamodb:Query
              Resource: arn:aws:dynamodb:*:*:table/spot*
        Roles:
          - Ref: IamRoleLambdaExecution

